export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_TEMPLATE_SUCCESS = 'LOAD_TEMPLATE_SUCCESS';
export const CREATE_TEMPLATE_SUCCESS = 'CREATE_TEMPLATE_SUCCESS';
export const UPDATE_TEMPLATE_SUCCESS = 'UPDATE_TEMPLATE_SUCCESS';
export const DELETE_TEMPLATE_SUCCESS = 'DELETE_TEMPLATE_SUCCESS';

export const CREATE_CHECKOUT_SUCCESS = 'CREATE_CHECKOUT_SUCCESS';
export const DELETE_CHECKOUT_SUCCESS = 'DELETE_CHECKOUT_SUCCESS';

export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';

export const USER_LOGOUT = 'USER_LOGOUT';