export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_TEMPLATE_SUCCESS = 'LOAD_TEMPLATE_SUCCESS';
export const CREATE_TEMPLATE_SUCCESS = 'CREATE_TEMPLATE_SUCCESS';
export const UPDATE_TEMPLATE_SUCCESS = 'UPDATE_TEMPLATE_SUCCESS';
export const DELETE_TEMPLATE_SUCCESS = 'DELETE_TEMPLATE_SUCCESS';

export const CREATE_CHECKOUT_SUCCESS = 'CREATE_CHECKOUT_SUCCESS';
export const DELETE_CHECKOUT_SUCCESS = 'DELETE_CHECKOUT_SUCCESS';

export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';

export const USER_LOGOUT = 'USER_LOGOUT';

export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const RECORD_RESULT = "RECORD_RESULT";
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_GOODS = 'ADD_TO_GOODS';
export const INVOICE_DETAILS ='INVOICE_DETAILS';
export const UPDATE_DETAILS = 'UPDATE_DETAILS'; 
export const DOWNLOAD_INVOICE = 'DOWNLOAD_INVOICE';
export const DELETE_PRODUCT = 'DELETE_PRODUCT ';

